create table if not exists public.battle_events (
  id bigint generated by default as identity primary key,
  battle_id uuid not null references public.battles(id) on delete cascade,
  event_type text not null check (event_type in ('challenge_created', 'challenge_shared', 'opponent_joined')),
  created_at timestamptz not null default now(),
  unique (battle_id, event_type)
);

create index if not exists battle_events_created_at_idx on public.battle_events (created_at desc);

alter table public.battle_events enable row level security;
revoke all on public.battle_events from anon, authenticated;
grant all on public.battle_events to service_role;
grant usage, select on all sequences in schema public to service_role;
