create table if not exists public.drafts (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users(id) on delete set null,
  guest_session_hash text,
  wallet_address text,
  status text not null default 'virtual' check (status in ('virtual', 'owned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint drafts_have_owner check (owner_user_id is not null or guest_session_hash is not null)
);

create table if not exists public.draft_picks (
  id bigint generated by default as identity primary key,
  draft_id uuid not null references public.drafts(id) on delete cascade,
  ticker text not null,
  virtual_amount integer not null check (virtual_amount > 0),
  position smallint not null check (position between 1 and 5),
  unique (draft_id, ticker),
  unique (draft_id, position)
);

create table if not exists public.purchase_attempts (
  id uuid primary key default gen_random_uuid(),
  draft_id uuid not null references public.drafts(id) on delete cascade,
  ticker text not null,
  allocation_cents integer not null check (allocation_cents > 0),
  status text not null default 'ready' check (status in ('ready', 'submitted', 'confirmed', 'failed')),
  transaction_hash text,
  balance_before numeric(78,0),
  balance_after numeric(78,0),
  balance_verified boolean not null default false,
  confirmed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.battles (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'waiting' check (status in ('waiting', 'active', 'complete')),
  ownership_status text not null default 'virtual' check (ownership_status in ('virtual', 'owned')),
  player_wallet_address text,
  opponent_wallet_address text,
  player_picks jsonb not null,
  opponent_picks jsonb,
  opening_prices jsonb,
  end_prices jsonb,
  starts_at timestamptz,
  ends_at timestamptz,
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  constraint battle_window_valid check ((status = 'waiting' and starts_at is null and ends_at is null) or (starts_at is not null and ends_at > starts_at)),
  constraint active_battle_has_opening check (status = 'waiting' or (opening_prices is not null and starts_at is not null and ends_at is not null)),
  constraint completed_battle_has_prices check (status <> 'complete' or (end_prices is not null and settled_at is not null))
);

create table if not exists public.battle_price_snapshots (
  id bigint generated by default as identity primary key,
  battle_id uuid not null references public.battles(id) on delete cascade,
  kind text not null check (kind in ('start', 'current', 'end')),
  prices jsonb not null,
  captured_at timestamptz not null default now()
);

create index if not exists purchase_attempts_draft_id_idx on public.purchase_attempts (draft_id);
create index if not exists battles_ends_at_idx on public.battles (ends_at) where status <> 'complete';
create index if not exists battle_price_snapshots_battle_id_idx on public.battle_price_snapshots (battle_id, captured_at desc);

alter table public.drafts enable row level security;
alter table public.draft_picks enable row level security;
alter table public.purchase_attempts enable row level security;
alter table public.battles enable row level security;
alter table public.battle_price_snapshots enable row level security;

revoke all on public.drafts, public.draft_picks, public.purchase_attempts, public.battles, public.battle_price_snapshots from anon, authenticated;
grant all on public.drafts, public.draft_picks, public.purchase_attempts, public.battles, public.battle_price_snapshots to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.record_battle_price_snapshot()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' and new.opening_prices is not null then
    insert into public.battle_price_snapshots (battle_id, kind, prices, captured_at)
    values (new.id, 'start', new.opening_prices, new.starts_at);
  elsif tg_op = 'UPDATE' and old.opening_prices is null and new.opening_prices is not null then
    insert into public.battle_price_snapshots (battle_id, kind, prices, captured_at)
    values (new.id, 'start', new.opening_prices, new.starts_at);
  end if;
  if tg_op = 'UPDATE' and old.end_prices is null and new.end_prices is not null then
    insert into public.battle_price_snapshots (battle_id, kind, prices, captured_at)
    values (new.id, 'end', new.end_prices, coalesce(new.settled_at, now()));
  end if;
  return new;
end;
$$;

revoke execute on function public.record_battle_price_snapshot() from public, anon, authenticated;

drop trigger if exists battle_price_snapshot_trigger on public.battles;
create trigger battle_price_snapshot_trigger
after insert or update of opening_prices, end_prices on public.battles
for each row execute function public.record_battle_price_snapshot();

create or replace function public.set_record_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke execute on function public.set_record_updated_at() from public, anon, authenticated;

drop trigger if exists drafts_updated_at_trigger on public.drafts;
create trigger drafts_updated_at_trigger before update on public.drafts
for each row execute function public.set_record_updated_at();

drop trigger if exists purchase_attempts_updated_at_trigger on public.purchase_attempts;
create trigger purchase_attempts_updated_at_trigger before update on public.purchase_attempts
for each row execute function public.set_record_updated_at();
